export const privacyPolicy = {
    title: "Gyosu Privacy Policy",
    content: [
        {
            title: "1. Introduction",
            text: "Welcome to Gyosu. We respect your privacy and want to protect your personal information. This Privacy Policy explains how we collect, store, and use your personal information when you use our application."
        },
        {
            title: "2. Data Collection",
            text: "We collect data that you provide directly to us when you use our tools. The data we collect only includes the information you input into our tools and the ratings you provide about the quality of our responses."
        },
        {
            title: "3. Use of Data",
            text: "We use the data you provide to deliver the functionality of our tools, generate responses, and improve our products based on your ratings and feedback."
        },
        {
            title: "4. Data Sharing",
            text: "We do not share your data with third parties for marketing, personalization, or other purposes. We do not have any advertising partners as of the time this policy was written."
        },
        {
            title: "5. Cookies and Tracking Technologies",
            text: "At present, we do not use cookies or other tracking technologies. However, we may request location data for certain tools if it is necessary for the tool's functionality."
        },
        {
            title: "6. Control Over Your Data",
            text: "You can request the deletion of your profile and associated data by emailing us at wingman@flybyai.io."
        },
        {
            title: "7. Data Security",
            text: "We take the protection of your data seriously. We use protected authentication solutions for login and a secure database for storing your input and responses to our tools."
        },
        {
            title: "8. Data Collection from Minors",
            text: "Gyosu does not knowingly collect or solicit personal information from anyone under the age of 13. If you are under 13, please do not attempt to use Gyosu or send any personal information about yourself to us."
        },
        {
            title: "9. International Users",
            text: "Our application is accessible to users worldwide. We strive to comply with all applicable data protection and privacy laws and regulations as they apply to our international users."
        },
        {
            title: "10. Contact Information",
            text: "If you have any questions about this Privacy Policy, please contact us at wingman@Gyosu.io."
        }
    ]
};


export const termsOfUse = {
    title: "Gyosu Terms of Use",
    content: [
        {
            title: "1. Acceptance of Terms",
            text: "By using the Gyosu application, you agree to the following Terms of Use. If you do not agree with these terms, please do not access or use this application."
        },
        {
            title: "2. Use License",
            text: "Gyosu grants you a limited, personal, non-exclusive, and non-transferable license to use its tools for personal, non-commercial use. However, for users with an active paid subscription, you are granted a license to use the responses generated by our tools for commercial purposes as long as your subscription is active. You are not allowed to modify, distribute, reproduce, or reverse-engineer the application."
        },
        {
            title: "3. Intellectual Property Rights",
            text: "All rights, titles, and interests in and to the application (including any and all copyrights, patents, and any other protected status) belong to Gyosu. You agree to abide by all copyright notices, information, or restrictions contained in or attached to any part of our application."
        },
        {
            title: "4. User Conduct",
            text: "You agree to use our application responsibly and in compliance with all applicable laws. You are responsible for all of your activity in connection with the application."
        },
        {
            title: "5. Termination",
            text: "Gyosu reserves the right to terminate or suspend your access to the application at any time, with or without notice, for any violation of these Terms of Use."
        },
        {
            title: "6. Changes to Terms",
            text: "We reserve the right to modify or replace these Terms of Use at any time. Your continued use of the site after any such changes constitutes your acceptance of the new Terms of Use."
        },
        {
            title: "7. Contact Information",
            text: "If you have any questions about these Terms of Use, please contact us at wingman@Gyosu.io."
        }
    ]
};

